# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'ded18923-115b-46b4-9d26-2b4032056186'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmpipeline1711'
    location: 'Australia Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/krishna-ms-git/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json.txt'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
